# Database Configuration
spring.data.mongodb:
  host: javis-server
  port: 27017
  database: api_throttle
  #username:
  #password:

# Cache
spring.cache:
  type: redis
  redis:
    time-to-live: 600000

# Redis
spring.redis:
  host: javis-server
  port: 6379

# Kafka Configuration
spring.cloud.stream.kafka:
  binder:
    brokers: javis-server

# Channel configuration
spring.cloud.stream.bindings:
  api-throttle-bucket-status-error:
    content-type: application/json
  api-throttle-bucket-empty:
    content-type: application/json